#!/usr/bin/env bash
# vim: set ft=sh

set -exuo pipefail

DIR="$PWD"
GARDEN_VERSION="$( cat "${DIR}/gr-version/number" )"
# CANDIDATE_DIR="${DIR}/gr-candidate-tarball"
RELEASE_YML="${DIR}/gr-release-develop/releases/garden-runc/garden-runc-${GARDEN_VERSION}.yml"
FINAL_TARBALL_PATH="${DIR}/final-release/garden-runc-${GARDEN_VERSION}.tgz"
DRY_RUN="${DRY_RUN:-true}"

function configure_git() {
  git config --global user.email "ci@localhost"
  git config --global user.name "CI Bot"
}

function configure_blobstore_credentials() {
  cp "${DIR}/garden-ci/config/private.yml" "${DIR}/gr-release-develop/config/private.yml"
}

# function commit_final_release() {
#   git add -A
#   git commit -m "release v${GARDEN_VERSION}"
# }

function finalize_release() {
  if [ "$DRY_RUN" != "false" ]; then return; fi

  echo "finalizing release"
  # bosh -n finalize-release --dir="${DIR}/gr-release-develop" --sha2 --version "$GARDEN_VERSION" "${CANDIDATE_DIR}/garden-runc-*.tgz"
  # mv "${CANDIDATE_DIR}"/garden-runc-*.tgz "$(dirname "$FINAL_TARBALL_PATH")"
}

function create_final_release() {
  if [ -e "$RELEASE_YML" ]; then
    echo "release already created; making tarball..."
    bosh -n create-release --dir="${DIR}/gr-release-develop" --sha2 --tarball="$FINAL_TARBALL_PATH" "$RELEASE_YML"
  else
    finalize_release
  fi

  # cp -r "${DIR}/gr-release/develop" "${DIR}/release/master"
}

if [ -z "${GARDEN_VERSION:-}" ]; then
  echo "missing garden version number" 1>&2
  exit 1
fi

configure_blobstore_credentials
configure_git
create_final_release
exit 1

# # prepare github release
# mv gdn-linux-release/gdn "github-release/gdn-${GARDEN_VERSION}"
